export const HARVII_MARKETING_URL = process.env.NEXT_PUBLIC_HARVII_MARKETING_URL || 'https://harvii.co'
export const HARVII_DOMAIN = process.env.NEXT_PUBLIC_HARVII_DOMAIN || 'harvii.shop'
export const DEV_SLUG = process.env.NEXT_PUBLIC_DEV_SLUG || 'demo'
export const API_URL = process.env.NEXT_PUBLIC_API_URL || 'https://hapi.xoroai.cloud'
export const CURRENCY_SYMBOL = process.env.NEXT_PUBLIC_CURRENCY_SYMBOL || '$'
